import { a as buildSearchIndex, b as parseMarkdownVariant, g as serializeCuration, h as parseCurationFile, l as CURATION_FILE_NAME, m as parseCorpusIndex, o as searchCorpus, p as mergeCuration, t as CORPUS_LOCALES, u as CURATION_HOME_DIR } from "./core-xQuT5Wq_.js";
import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import z from "schemastery";
import { dshHomePath } from "@deepseek-ai/dsh-paths";
//#region types/app/index.js
/**
* DSH 101 host service: corpus loading, search, curation status, and atomic
* curation publish, plus the `/api/dsh101` HTTP routes.
*
* The corpus ships inside this package's `assets/` directory (generated by
* `scripts/gen-dsh-101-corpus.ts`); a missing corpus degrades to an empty
* index so the reader stays usable and the curator workflow can bootstrap.
*
* @module @deepseek-ai/dsh-101-app
*/
/** Plugin name. */
const name = "dsh-101-app";
/** Services required by the host half. */
const inject = ["httpServer"];
const Config = z.object({ corpusDir: z.string() });
/** Default corpus directory: `assets/dsh-101` next to this package. */
const DEFAULT_CORPUS_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "assets", "dsh-101");
/**
* File name of the reader's own "last confirmed corpus revision" state
* (`$DSH_HOME/dsh-101/last-seen-revision.json`). Unlike the curation overlay
* (which only exists once the user publishes one), this state is written on
* the reader's first boot and after every curation publish, so a DSH upgrade
* that changes the corpus revision is detectable even when no overlay was
* ever published.
*/
const SEEN_REVISION_FILE_NAME = "last-seen-revision.json";
/** Empty corpus used when the generated assets are absent (bootstrapping). */
const EMPTY_CORPUS = {
	schemaVersion: 1,
	dshVersion: "0.0.0",
	revision: "empty",
	modules: [],
	documents: {}
};
/** The `ctx.dsh101` service implementation. */
var Dsh101Service = class {
	ctx;
	corpusDir;
	corpus;
	curation;
	jobToken;
	#docs = /* @__PURE__ */ new Map();
	#search = [];
	#contexts = /* @__PURE__ */ new Map();
	translationsDir;
	/** docId -> translation-session binding (loaded from the harness home). */
	#translationBindings = /* @__PURE__ */ new Map();
	constructor(ctx, corpusDir) {
		this.ctx = ctx;
		this.corpusDir = corpusDir;
		this.jobToken = randomUUID();
		this.corpus = this.#loadCorpus();
		this.curation = this.#loadCuration();
		this.translationsDir = join(dshHomePath(CURATION_HOME_DIR), "translations");
		this.#loadTranslationBindings();
		this.#rebuild();
		this.#cleanupSupersededAll();
	}
	doc(id) {
		return this.#docs.get(id);
	}
	async docFull(id) {
		const doc = this.#docs.get(id);
		if (doc === void 0) return void 0;
		const full = await readDocumentFile(this.corpusDir, id);
		const merged = full === void 0 ? doc : {
			...doc,
			variants: full.variants
		};
		for (const locale of CORPUS_LOCALES) {
			if (merged.variants[locale] === void 0) continue;
			await this.#cleanupSuperseded(id, locale);
		}
		for (const locale of CORPUS_LOCALES) {
			if (merged.variants[locale] !== void 0) continue;
			const translation = await this.#readTranslation(id, locale);
			if (translation !== void 0) merged.variants[locale] = translation;
		}
		return merged;
	}
	/**
	* Remove a user translation the official corpus now supersedes: the user
	* file under the harness home and its session binding (matching locale).
	* Missing files are tolerated (ENOENT is the normal already-clean state).
	*/
	async #cleanupSuperseded(docId, locale) {
		try {
			await rm(join(this.translationsDir, docId, `${locale}.md`));
		} catch (error) {
			if (error.code !== "ENOENT") throw error;
		}
		const binding = this.#translationBindings.get(docId);
		if (binding !== void 0 && binding.locale === locale) {
			this.#translationBindings.delete(docId);
			await this.#saveTranslationBindings();
		}
	}
	/** Full-corpus pass over every document the corpus index knows. */
	async #cleanupSupersededAll() {
		for (const docId of this.#docs.keys()) {
			const doc = this.#docs.get(docId);
			if (doc === void 0) continue;
			for (const locale of CORPUS_LOCALES) {
				if (doc.variants[locale] === void 0) continue;
				await this.#cleanupSuperseded(docId, locale);
			}
		}
	}
	/** Read a user translation file for one document/locale, if present. */
	async #readTranslation(docId, locale) {
		try {
			const parsed = parseMarkdownVariant(await readFile(join(this.translationsDir, docId, `${locale}.md`), "utf8"));
			return {
				title: parsed.title,
				summary: parsed.summary,
				body: parsed.body,
				sections: parsed.sections
			};
		} catch (error) {
			if (error.code !== "ENOENT") throw error;
			return;
		}
	}
	setContext(sessionId, context) {
		this.#contexts.set(sessionId, context);
	}
	getContext(sessionId) {
		return this.#contexts.get(sessionId);
	}
	async saveTranslation(input) {
		if (!this.#docs.has(input.docId)) return {
			ok: false,
			error: `unknown document ${JSON.stringify(input.docId)}`
		};
		if (input.locale !== "en" && input.locale !== "zh") return {
			ok: false,
			error: "locale must be en or zh"
		};
		if (input.body.trim() === "") return {
			ok: false,
			error: "translation body is empty"
		};
		if (this.#docs.get(input.docId)?.variants[input.locale] !== void 0) return {
			ok: false,
			error: `document already has a ${input.locale} variant`
		};
		const dir = join(this.translationsDir, input.docId);
		await mkdir(dir, { recursive: true });
		const target = join(dir, `${input.locale}.md`);
		const tmp = `${target}.tmp-${Math.random().toString(36).slice(2, 8)}`;
		await writeFile(tmp, input.body, "utf8");
		await rename(tmp, target);
		return { ok: true };
	}
	async bindTranslation(input) {
		if (!this.#docs.has(input.docId)) return {
			ok: false,
			error: `unknown document ${JSON.stringify(input.docId)}`
		};
		if (input.sessionId === "") return {
			ok: false,
			error: "sessionId must not be empty"
		};
		if (input.locale !== "en" && input.locale !== "zh") return {
			ok: false,
			error: "locale must be en or zh"
		};
		this.#translationBindings.set(input.docId, {
			sessionId: input.sessionId,
			locale: input.locale,
			title: input.title,
			updatedAt: Date.now()
		});
		await this.#saveTranslationBindings();
		return { ok: true };
	}
	translationBindings() {
		return Object.fromEntries(this.#translationBindings);
	}
	/** The bindings file path: `$DSH_HOME/dsh-101/translation-bindings.json`. */
	#bindingsPath() {
		return join(dshHomePath(CURATION_HOME_DIR), "translation-bindings.json");
	}
	#loadTranslationBindings() {
		try {
			const bindings = JSON.parse(readFileSync(this.#bindingsPath(), "utf8")).bindings;
			if (bindings === null || typeof bindings !== "object" || Array.isArray(bindings)) return;
			for (const [docId, value] of Object.entries(bindings)) {
				if (typeof value !== "object" || value === null) continue;
				const record = value;
				if (typeof record.sessionId !== "string" || typeof record.locale !== "string") continue;
				if (record.locale !== "en" && record.locale !== "zh") continue;
				this.#translationBindings.set(docId, {
					sessionId: record.sessionId,
					locale: record.locale,
					title: typeof record.title === "string" ? record.title : docId,
					updatedAt: typeof record.updatedAt === "number" ? record.updatedAt : 0
				});
			}
		} catch (error) {
			if (error.code !== "ENOENT") this.ctx.logger.warn(`dsh-101: translation bindings unreadable: ${error instanceof Error ? error.message : String(error)}`);
		}
	}
	async #saveTranslationBindings() {
		await mkdir(dshHomePath(CURATION_HOME_DIR), { recursive: true });
		const target = this.#bindingsPath();
		const tmp = `${target}.tmp-${Math.random().toString(36).slice(2, 8)}`;
		await writeFile(tmp, JSON.stringify({
			schemaVersion: 1,
			bindings: Object.fromEntries(this.#translationBindings)
		}, null, 2), "utf8");
		await rename(tmp, target);
	}
	search(query) {
		return searchCorpus(this.#search, query);
	}
	async publish(input) {
		if (input.token !== this.jobToken) return {
			ok: false,
			error: "invalid or expired curation job token"
		};
		if (input.curation.schemaVersion !== this.corpus.schemaVersion) return {
			ok: false,
			error: `curation schemaVersion ${input.curation.schemaVersion} does not match corpus schemaVersion ${this.corpus.schemaVersion}`
		};
		if (input.curation.baseRevision !== this.corpus.revision) return {
			ok: false,
			error: `curation baseRevision ${input.curation.baseRevision} does not match corpus revision ${this.corpus.revision}`
		};
		const documents = input.curation.documents;
		if (documents !== void 0) {
			for (const id of Object.keys(documents)) if (!this.#docs.has(id)) return {
				ok: false,
				error: `curation references unknown document ${JSON.stringify(id)}`
			};
		}
		const home = dshHomePath(CURATION_HOME_DIR);
		await mkdir(home, { recursive: true });
		const target = join(home, CURATION_FILE_NAME);
		const tmp = join(home, `${CURATION_FILE_NAME}.tmp-${this.jobToken.slice(0, 8)}`);
		await writeFile(tmp, serializeCuration(input.curation), "utf8");
		await rename(tmp, target);
		this.curation.curation = input.curation;
		this.curation.current = true;
		this.curation.lastError = void 0;
		this.#saveSeenRevision(this.corpus.revision);
		this.#rebuild();
		return { ok: true };
	}
	#loadCorpus() {
		try {
			return parseCorpusIndex(readFileSync(join(this.corpusDir, "corpus.json"), "utf8"));
		} catch (error) {
			this.ctx.logger.warn(`dsh-101: corpus unavailable, using empty index: ${error instanceof Error ? error.message : String(error)}`);
			return EMPTY_CORPUS;
		}
	}
	#loadCuration() {
		const path = join(dshHomePath(CURATION_HOME_DIR), CURATION_FILE_NAME);
		try {
			const curation = parseCurationFile(readFileSync(path, "utf8"));
			return {
				curation,
				current: curation.baseRevision === this.corpus.revision
			};
		} catch (error) {
			if (error.code !== "ENOENT") this.ctx.logger.warn(`dsh-101: curation overlay unreadable: ${error instanceof Error ? error.message : String(error)}`);
			const seenRevision = this.#loadSeenRevision();
			if (seenRevision === void 0) {
				this.#saveSeenRevision(this.corpus.revision);
				return {
					curation: void 0,
					current: true
				};
			}
			return {
				curation: void 0,
				current: seenRevision === this.corpus.revision
			};
		}
	}
	/** The reader's own "last confirmed corpus revision" state path. */
	#seenRevisionPath() {
		return join(dshHomePath(CURATION_HOME_DIR), SEEN_REVISION_FILE_NAME);
	}
	/** Read the last confirmed corpus revision; undefined when absent/unreadable. */
	#loadSeenRevision() {
		try {
			const raw = JSON.parse(readFileSync(this.#seenRevisionPath(), "utf8"));
			return typeof raw.revision === "string" && raw.revision !== "" ? raw.revision : void 0;
		} catch (error) {
			if (error.code !== "ENOENT") this.ctx.logger.warn(`dsh-101: seen-revision state unreadable: ${error instanceof Error ? error.message : String(error)}`);
			return;
		}
	}
	/** Persist the corpus revision the reader has confirmed (atomic rename). */
	#saveSeenRevision(revision) {
		mkdirSync(dshHomePath(CURATION_HOME_DIR), { recursive: true });
		const target = this.#seenRevisionPath();
		const tmp = `${target}.tmp-${Math.random().toString(36).slice(2, 8)}`;
		writeFileSync(tmp, JSON.stringify({
			schemaVersion: 1,
			revision,
			updatedAt: Date.now()
		}, null, 2), "utf8");
		try {
			renameSync(tmp, target);
		} catch (error) {
			this.ctx.logger.warn(`dsh-101: seen-revision state write failed: ${error instanceof Error ? error.message : String(error)}`);
			rmSync(tmp, { force: true });
		}
	}
	#rebuild() {
		const merged = mergeCuration(this.corpus, this.curation.curation);
		this.#docs = new Map(Object.entries(merged.documents));
		this.#search = buildSearchIndex(merged);
	}
};
/** Extension -> content type for the image route. */
const IMAGE_MIME = {
	".png": "image/png",
	".jpg": "image/jpeg",
	".jpeg": "image/jpeg",
	".gif": "image/gif",
	".svg": "image/svg+xml",
	".webp": "image/webp",
	".avif": "image/avif",
	".ico": "image/x-icon"
};
function mimeOf(file) {
	const dot = file.lastIndexOf(".");
	return IMAGE_MIME[dot >= 0 ? file.slice(dot) : ""] ?? "application/octet-stream";
}
/** JSON response helper. */
function json(res, status, value) {
	const body = JSON.stringify(value);
	res.writeHead(status, { "content-type": "application/json; charset=utf-8" });
	res.end(body);
}
/** Read one document's full body file (variants merged), or undefined when absent. */
async function readDocumentFile(corpusDir, id) {
	try {
		const raw = await readFile(join(corpusDir, "documents", `${id}.json`), "utf8");
		const parsed = JSON.parse(raw);
		return {
			id: parsed.id,
			module: "",
			kind: "misc",
			sourcePath: "",
			variants: parsed.variants
		};
	} catch (error) {
		if (error.code !== "ENOENT") throw error;
		return;
	}
}
/** Parse a JSON request body (bounded). */
async function readJson(req) {
	const chunks = [];
	let size = 0;
	for await (const chunk of req) {
		const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
		size += buffer.length;
		if (size > 1e6) throw new Error("request body too large");
		chunks.push(buffer);
	}
	return JSON.parse(Buffer.concat(chunks).toString("utf8"));
}
/** Mount the plugin. */
function apply(ctx, config = {}) {
	const service = new Dsh101Service(ctx, config.corpusDir ?? DEFAULT_CORPUS_DIR);
	ctx.effect(() => {
		const disposeService = ctx.reflect.provide("dsh101", service);
		return () => {
			disposeService();
		};
	}, "dsh-101-app: service");
	const handle = async (req, res) => {
		const url = new URL(req.url ?? "/", "http://dsh.internal");
		const path = url.pathname.replace(/^\/api\/dsh101/, "") || "/";
		try {
			if (req.method === "GET" && path === "/index") {
				json(res, 200, {
					corpus: service.corpus,
					curationCurrent: service.curation.current
				});
				return;
			}
			if (req.method === "GET" && path.startsWith("/doc/")) {
				const id = decodeURIComponent(path.slice(5));
				const doc = await service.docFull(id);
				if (doc === void 0) {
					json(res, 404, { error: `unknown document ${JSON.stringify(id)}` });
					return;
				}
				json(res, 200, { doc });
				return;
			}
			if (req.method === "GET" && path.startsWith("/search")) {
				const query = url.searchParams.get("q") ?? "";
				json(res, 200, { result: service.search(query) });
				return;
			}
			if (req.method === "GET" && path.startsWith("/img/")) {
				const file = path.slice(5).replace(/[^a-zA-Z0-9._-]/g, "");
				try {
					const data = await readFile(join(service.corpusDir, "images", file));
					res.writeHead(200, {
						"content-type": mimeOf(file),
						"cache-control": "public, max-age=31536000, immutable"
					});
					res.end(data);
				} catch {
					json(res, 404, { error: "image not found" });
				}
				return;
			}
			if (req.method === "GET" && path === "/status") {
				json(res, 200, {
					corpusRevision: service.corpus.revision,
					dshVersion: service.corpus.dshVersion,
					curation: service.curation,
					jobToken: service.jobToken
				});
				return;
			}
			if (req.method === "GET" && path.startsWith("/context")) {
				const sessionId = url.searchParams.get("sessionId") ?? "";
				json(res, 200, { context: sessionId === "" ? void 0 : service.getContext(sessionId) ?? null });
				return;
			}
			if (req.method === "POST" && path === "/context") {
				const body = await readJson(req);
				if (typeof body.sessionId !== "string" || typeof body.docId !== "string") {
					json(res, 400, { error: "sessionId and docId are required" });
					return;
				}
				service.setContext(body.sessionId, {
					docId: body.docId,
					...typeof body.section === "string" ? { section: body.section } : {}
				});
				json(res, 200, { ok: true });
				return;
			}
			if (req.method === "POST" && path === "/translate") {
				const body = await readJson(req);
				if (typeof body.docId !== "string" || typeof body.locale !== "string" || typeof body.translation !== "string") {
					json(res, 400, { error: "docId, locale, and translation are required" });
					return;
				}
				const result = await service.saveTranslation({
					docId: body.docId,
					locale: body.locale,
					body: body.translation
				});
				json(res, result.ok ? 200 : 400, result);
				return;
			}
			if (req.method === "GET" && path === "/translations") {
				json(res, 200, { bindings: service.translationBindings() });
				return;
			}
			if (req.method === "POST" && path === "/translate/bind") {
				const body = await readJson(req);
				if (typeof body.docId !== "string" || typeof body.sessionId !== "string" || typeof body.locale !== "string") {
					json(res, 400, { error: "docId, sessionId, and locale are required" });
					return;
				}
				const result = await service.bindTranslation({
					docId: body.docId,
					sessionId: body.sessionId,
					locale: body.locale,
					title: typeof body.title === "string" ? body.title : body.docId
				});
				json(res, result.ok ? 200 : 400, result);
				return;
			}
			if (req.method === "POST" && path === "/publish") {
				const body = await readJson(req);
				const token = typeof body.token === "string" ? body.token : "";
				const curation = typeof body.curation === "object" && body.curation !== null ? parseCurationFile(JSON.stringify(body.curation)) : void 0;
				if (curation === void 0) {
					json(res, 400, { error: "missing curation payload" });
					return;
				}
				const result = await service.publish({
					token,
					curation
				});
				json(res, result.ok ? 200 : 400, result);
				return;
			}
			json(res, 404, { error: `unknown dsh101 endpoint ${JSON.stringify(path)}` });
		} catch (error) {
			json(res, 500, { error: error instanceof Error ? error.message : String(error) });
		}
	};
	ctx.effect(() => ctx.httpServer.register({
		kind: "prefix",
		path: "/api/dsh101",
		handler: handle
	}), "dsh-101-app: api routes");
}
//#endregion
export { Config, Dsh101Service, apply, inject, name };
