/**
 * DSH 101 host service: corpus loading, search, curation status, and atomic
 * curation publish, plus the `/api/dsh101` HTTP routes.
 *
 * The corpus ships inside this package's `assets/` directory (generated by
 * `scripts/gen-dsh-101-corpus.ts`); a missing corpus degrades to an empty
 * index so the reader stays usable and the curator workflow can bootstrap.
 *
 * @module @deepseek-ai/dsh-101-app
 */

import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises'
import { randomUUID } from 'node:crypto'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Context } from 'cordis'
import z from 'schemastery'
import {
  buildSearchIndex,
  CORPUS_LOCALES,
  CURATION_FILE_NAME,
  CURATION_HOME_DIR,
  type CorpusIndex,
  type CorpusLocale,
  type CurationFile,
  type DocEntry,
  type DocVariant,
  type SearchResult,
  mergeCuration,
  parseCorpusIndex,
  parseCurationFile,
  parseMarkdownVariant,
  searchCorpus,
  serializeCuration,
} from '../core/index.ts'
import { dshHomePath } from '@deepseek-ai/dsh-paths'
import type {} from '@deepseek-ai/dsh-host-webserver'
import type { IncomingMessage, ServerResponse } from 'node:http'

/** Plugin name. */
export const name = 'dsh-101-app'

/** Services required by the host half. */
export const inject = ['httpServer']

/** Plugin config. */
export interface Config {
  /** Directory holding the generated corpus (defaults to this package's assets/). */
  corpusDir?: string
}

export const Config: z<Config> = z.object({
  corpusDir: z.string(),
})

/** Default corpus directory: `assets/dsh-101` next to this package. */
const DEFAULT_CORPUS_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'assets', 'dsh-101')

/**
 * File name of the reader's own "last confirmed corpus revision" state
 * (`$DSH_HOME/dsh-101/last-seen-revision.json`). Unlike the curation overlay
 * (which only exists once the user publishes one), this state is written on
 * the reader's first boot and after every curation publish, so a DSH upgrade
 * that changes the corpus revision is detectable even when no overlay was
 * ever published.
 */
const SEEN_REVISION_FILE_NAME = 'last-seen-revision.json'

/** Empty corpus used when the generated assets are absent (bootstrapping). */
const EMPTY_CORPUS: CorpusIndex = {
  schemaVersion: 1,
  dshVersion: '0.0.0',
  revision: 'empty',
  modules: [],
  documents: {},
}

interface CurationState {
  /** Current overlay, or undefined when none is published. */
  curation: CurationFile | undefined
  /** True when the published overlay matches the corpus revision. */
  current: boolean
  /** Human-readable publish error from the last attempt (undefined when none). */
  lastError?: string | undefined
}

/**
 * The dsh101 service face.
 */
export interface IDsh101 {
  /** The loaded corpus (merged with the published curation overlay). */
  readonly corpus: CorpusIndex
  /** Curation overlay state. */
  readonly curation: CurationState
  /** Current curation job token (rotated per publish). */
  readonly jobToken: string
  /** Look up one document by id; returns undefined when absent. */
  doc(id: string): DocEntry | undefined
  /** Look up one document with its full bodies loaded from the document files; undefined when absent. */
  docFull(id: string): Promise<DocEntry | undefined>
  /** Search the corpus. */
  search(query: string): SearchResult
  /** Set the tutor reading context for one session (article id + optional section). */
  setContext(sessionId: string, context: TutorContext): void
  /** Read the tutor reading context for one session. */
  getContext(sessionId: string): TutorContext | undefined
  /**
   * Persist a user translation for a document under the harness home
   * (`$DSH_HOME/dsh-101/translations/<docId>/<locale>.md`) — the source repo
   * is never touched. Only locales missing from the corpus are accepted, so
   * shipped translations cannot be overwritten.
   */
  saveTranslation(input: { docId: string; locale: CorpusLocale; body: string }): Promise<{ ok: true } | { ok: false; error: string }>
  /**
   * Bind a translation session to a document. The mapping persists under the
   * harness home (`$DSH_HOME/dsh-101/translation-bindings.json`) so a later
   * visit to the document can reopen the same session for adjustments.
   */
  bindTranslation(input: {
    docId: string
    sessionId: string
    locale: CorpusLocale
    title: string
  }): Promise<{ ok: true } | { ok: false; error: string }>
  /** All translation-session bindings, keyed by document id (docId -> binding). */
  translationBindings(): Readonly<Record<string, TranslationBinding>>
  /**
   * Publish a curation overlay. Validates schema, base revision, and
   * referenced document ids, then atomically replaces the overlay file.
   */
  publish(input: { token: string; curation: CurationFile }): Promise<{ ok: true } | { ok: false; error: string }>
}

/** One translation-session binding: the session id + locale + title of the
 *  translation conversation that produced (or is producing) a document's
 *  user translation. */
export interface TranslationBinding {
  sessionId: string
  locale: CorpusLocale
  title: string
  updatedAt: number
}

/** The reader's current article context for one tutor session. */
export interface TutorContext {
  docId: string
  section?: string
}

/** The `ctx.dsh101` service implementation. */
export class Dsh101Service implements IDsh101 {
  readonly corpus: CorpusIndex
  readonly curation: CurationState
  readonly jobToken: string
  #docs = new Map<string, DocEntry>()
  #search: ReturnType<typeof buildSearchIndex> = []
  #contexts = new Map<string, TutorContext>()
  readonly translationsDir: string
  /** docId -> translation-session binding (loaded from the harness home). */
  #translationBindings = new Map<string, TranslationBinding>()

  constructor(
    private readonly ctx: Context,
    readonly corpusDir: string,
  ) {
    this.jobToken = randomUUID()
    this.corpus = this.#loadCorpus()
    this.curation = this.#loadCuration()
    this.translationsDir = join(dshHomePath(CURATION_HOME_DIR), 'translations')
    this.#loadTranslationBindings()
    this.#rebuild()
    // Official translations ship inside the corpus: any user translation a
    // locale the corpus now provides is superseded — clean it up so stale
    // files and bindings cannot resurface later.
    void this.#cleanupSupersededAll()
  }

  doc(id: string): DocEntry | undefined {
    return this.#docs.get(id)
  }

  async docFull(id: string): Promise<DocEntry | undefined> {
    const doc = this.#docs.get(id)
    if (doc === undefined) return undefined
    const full = await readDocumentFile(this.corpusDir, id)
    const merged: DocEntry = full === undefined ? doc : { ...doc, variants: full.variants }
    // Official-variant check drives both merge and cleanup: a locale the
    // corpus provides wins over any user translation, and superseded user
    // files/bindings are removed (lazy fallback for runtime curation updates).
    for (const locale of CORPUS_LOCALES) {
      if (merged.variants[locale] === undefined) continue
      await this.#cleanupSuperseded(id, locale)
    }
    // Merge user translations for locales the corpus lacks.
    for (const locale of CORPUS_LOCALES) {
      if (merged.variants[locale] !== undefined) continue
      const translation = await this.#readTranslation(id, locale)
      if (translation !== undefined) merged.variants[locale] = translation
    }
    return merged
  }

  /**
   * Remove a user translation the official corpus now supersedes: the user
   * file under the harness home and its session binding (matching locale).
   * Missing files are tolerated (ENOENT is the normal already-clean state).
   */
  async #cleanupSuperseded(docId: string, locale: CorpusLocale): Promise<void> {
    try {
      await rm(join(this.translationsDir, docId, `${locale}.md`))
    } catch (error) {
      if ((error as { code?: string }).code !== 'ENOENT') throw error
    }
    const binding = this.#translationBindings.get(docId)
    if (binding !== undefined && binding.locale === locale) {
      this.#translationBindings.delete(docId)
      await this.#saveTranslationBindings()
    }
  }

  /** Full-corpus pass over every document the corpus index knows. */
  async #cleanupSupersededAll(): Promise<void> {
    for (const docId of this.#docs.keys()) {
      const doc = this.#docs.get(docId)
      if (doc === undefined) continue
      for (const locale of CORPUS_LOCALES) {
        if (doc.variants[locale] === undefined) continue
        await this.#cleanupSuperseded(docId, locale)
      }
    }
  }

  /** Read a user translation file for one document/locale, if present. */
  async #readTranslation(docId: string, locale: CorpusLocale): Promise<DocVariant | undefined> {
    try {
      const raw = await readFile(join(this.translationsDir, docId, `${locale}.md`), 'utf8')
      const parsed = parseMarkdownVariant(raw)
      return { title: parsed.title, summary: parsed.summary, body: parsed.body, sections: parsed.sections }
    } catch (error) {
      if ((error as { code?: string }).code !== 'ENOENT') throw error
      return undefined
    }
  }

  setContext(sessionId: string, context: TutorContext): void {
    this.#contexts.set(sessionId, context)
  }

  getContext(sessionId: string): TutorContext | undefined {
    return this.#contexts.get(sessionId)
  }

  async saveTranslation(input: {
    docId: string
    locale: CorpusLocale
    body: string
  }): Promise<{ ok: true } | { ok: false; error: string }> {
    if (!this.#docs.has(input.docId)) return { ok: false, error: `unknown document ${JSON.stringify(input.docId)}` }
    if (input.locale !== 'en' && input.locale !== 'zh') return { ok: false, error: 'locale must be en or zh' }
    if (input.body.trim() === '') return { ok: false, error: 'translation body is empty' }
    // Only fill in missing locales; shipped translations stay authoritative.
    const doc = this.#docs.get(input.docId)
    if (doc?.variants[input.locale] !== undefined) {
      return { ok: false, error: `document already has a ${input.locale} variant` }
    }
    const dir = join(this.translationsDir, input.docId)
    await mkdir(dir, { recursive: true })
    const target = join(dir, `${input.locale}.md`)
    const tmp = `${target}.tmp-${Math.random().toString(36).slice(2, 8)}`
    await writeFile(tmp, input.body, 'utf8')
    await rename(tmp, target)
    return { ok: true }
  }

  async bindTranslation(input: {
    docId: string
    sessionId: string
    locale: CorpusLocale
    title: string
  }): Promise<{ ok: true } | { ok: false; error: string }> {
    if (!this.#docs.has(input.docId)) return { ok: false, error: `unknown document ${JSON.stringify(input.docId)}` }
    if (input.sessionId === '') return { ok: false, error: 'sessionId must not be empty' }
    if (input.locale !== 'en' && input.locale !== 'zh') return { ok: false, error: 'locale must be en or zh' }
    this.#translationBindings.set(input.docId, {
      sessionId: input.sessionId,
      locale: input.locale,
      title: input.title,
      updatedAt: Date.now(),
    })
    await this.#saveTranslationBindings()
    return { ok: true }
  }

  translationBindings(): Readonly<Record<string, TranslationBinding>> {
    return Object.fromEntries(this.#translationBindings)
  }

  /** The bindings file path: `$DSH_HOME/dsh-101/translation-bindings.json`. */
  #bindingsPath(): string {
    return join(dshHomePath(CURATION_HOME_DIR), 'translation-bindings.json')
  }

  #loadTranslationBindings(): void {
    try {
      const raw = JSON.parse(readFileSync(this.#bindingsPath(), 'utf8')) as {
        bindings?: Record<string, unknown>
      }
      const bindings = raw.bindings
      if (bindings === null || typeof bindings !== 'object' || Array.isArray(bindings)) return
      for (const [docId, value] of Object.entries(bindings)) {
        if (typeof value !== 'object' || value === null) continue
        const record = value as Record<string, unknown>
        if (typeof record.sessionId !== 'string' || typeof record.locale !== 'string') continue
        if (record.locale !== 'en' && record.locale !== 'zh') continue
        this.#translationBindings.set(docId, {
          sessionId: record.sessionId,
          locale: record.locale,
          title: typeof record.title === 'string' ? record.title : docId,
          updatedAt: typeof record.updatedAt === 'number' ? record.updatedAt : 0,
        })
      }
    } catch (error) {
      // Missing file is the normal first-run state.
      if ((error as { code?: string }).code !== 'ENOENT') {
        this.ctx.logger.warn(`dsh-101: translation bindings unreadable: ${error instanceof Error ? error.message : String(error)}`)
      }
    }
  }

  async #saveTranslationBindings(): Promise<void> {
    const home = dshHomePath(CURATION_HOME_DIR)
    await mkdir(home, { recursive: true })
    const target = this.#bindingsPath()
    const tmp = `${target}.tmp-${Math.random().toString(36).slice(2, 8)}`
    const payload = JSON.stringify({ schemaVersion: 1, bindings: Object.fromEntries(this.#translationBindings) }, null, 2)
    await writeFile(tmp, payload, 'utf8')
    await rename(tmp, target)
  }

  search(query: string): SearchResult {
    return searchCorpus(this.#search, query)
  }

  async publish(input: { token: string; curation: CurationFile }): Promise<{ ok: true } | { ok: false; error: string }> {
    if (input.token !== this.jobToken) {
      return { ok: false, error: 'invalid or expired curation job token' }
    }
    if (input.curation.schemaVersion !== this.corpus.schemaVersion) {
      return { ok: false, error: `curation schemaVersion ${input.curation.schemaVersion} does not match corpus schemaVersion ${this.corpus.schemaVersion}` }
    }
    if (input.curation.baseRevision !== this.corpus.revision) {
      return { ok: false, error: `curation baseRevision ${input.curation.baseRevision} does not match corpus revision ${this.corpus.revision}` }
    }
    const documents = input.curation.documents
    if (documents !== undefined) {
      for (const id of Object.keys(documents)) {
        if (!this.#docs.has(id)) {
          return { ok: false, error: `curation references unknown document ${JSON.stringify(id)}` }
        }
      }
    }
    const home = dshHomePath(CURATION_HOME_DIR)
    await mkdir(home, { recursive: true })
    const target = join(home, CURATION_FILE_NAME)
    const tmp = join(home, `${CURATION_FILE_NAME}.tmp-${this.jobToken.slice(0, 8)}`)
    await writeFile(tmp, serializeCuration(input.curation), 'utf8')
    await rename(tmp, target)
    this.curation.curation = input.curation
    this.curation.current = true
    this.curation.lastError = undefined
    // Publishing the overlay means the reader has confirmed the current
    // corpus, so future upgrades are detectable against this revision.
    this.#saveSeenRevision(this.corpus.revision)
    this.#rebuild()
    return { ok: true }
  }

  #loadCorpus(): CorpusIndex {
    try {
      const text = readFileSync(join(this.corpusDir, 'corpus.json'), 'utf8')
      return parseCorpusIndex(text)
    } catch (error) {
      this.ctx.logger.warn(`dsh-101: corpus unavailable, using empty index: ${error instanceof Error ? error.message : String(error)}`)
      return EMPTY_CORPUS
    }
  }

  #loadCuration(): CurationState {
    const path = join(dshHomePath(CURATION_HOME_DIR), CURATION_FILE_NAME)
    try {
      const curation = parseCurationFile(readFileSync(path, 'utf8'))
      return { curation, current: curation.baseRevision === this.corpus.revision }
    } catch (error) {
      // Missing file is the normal first-run state: no overlay is published,
      // and the reader is fully usable without one — the update banner only
      // appears when the corpus revision changed since the reader last
      // confirmed it (a real DSH upgrade changed the docs), regardless of
      // whether an overlay was ever published.
      if ((error as { code?: string }).code !== 'ENOENT') {
        this.ctx.logger.warn(`dsh-101: curation overlay unreadable: ${error instanceof Error ? error.message : String(error)}`)
      }
      const seenRevision = this.#loadSeenRevision()
      if (seenRevision === undefined) {
        // First boot (or unreadable state): adopt the current revision so a
        // fresh install does not nag, and persist it so a later upgrade is
        // detectable.
        this.#saveSeenRevision(this.corpus.revision)
        return { curation: undefined, current: true }
      }
      return { curation: undefined, current: seenRevision === this.corpus.revision }
    }
  }

  /** The reader's own "last confirmed corpus revision" state path. */
  #seenRevisionPath(): string {
    return join(dshHomePath(CURATION_HOME_DIR), SEEN_REVISION_FILE_NAME)
  }

  /** Read the last confirmed corpus revision; undefined when absent/unreadable. */
  #loadSeenRevision(): string | undefined {
    try {
      const raw = JSON.parse(readFileSync(this.#seenRevisionPath(), 'utf8')) as { revision?: unknown }
      return typeof raw.revision === 'string' && raw.revision !== '' ? raw.revision : undefined
    } catch (error) {
      if ((error as { code?: string }).code !== 'ENOENT') {
        this.ctx.logger.warn(`dsh-101: seen-revision state unreadable: ${error instanceof Error ? error.message : String(error)}`)
      }
      return undefined
    }
  }

  /** Persist the corpus revision the reader has confirmed (atomic rename). */
  #saveSeenRevision(revision: string): void {
    const home = dshHomePath(CURATION_HOME_DIR)
    mkdirSync(home, { recursive: true })
    const target = this.#seenRevisionPath()
    const tmp = `${target}.tmp-${Math.random().toString(36).slice(2, 8)}`
    writeFileSync(tmp, JSON.stringify({ schemaVersion: 1, revision, updatedAt: Date.now() }, null, 2), 'utf8')
    try {
      renameSync(tmp, target)
    } catch (error) {
      this.ctx.logger.warn(`dsh-101: seen-revision state write failed: ${error instanceof Error ? error.message : String(error)}`)
      rmSync(tmp, { force: true })
    }
  }

  #rebuild(): void {
    const merged = mergeCuration(this.corpus, this.curation.curation)
    this.#docs = new Map(Object.entries(merged.documents))
    this.#search = buildSearchIndex(merged)
  }
}

/** Extension -> content type for the image route. */
const IMAGE_MIME: Record<string, string> = {
  '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.gif': 'image/gif',
  '.svg': 'image/svg+xml', '.webp': 'image/webp', '.avif': 'image/avif', '.ico': 'image/x-icon',
}

function mimeOf(file: string): string {
  const dot = file.lastIndexOf('.')
  const ext = dot >= 0 ? file.slice(dot) : ''
  return IMAGE_MIME[ext] ?? 'application/octet-stream'
}

/** JSON response helper. */
function json(res: ServerResponse, status: number, value: unknown): void {
  const body = JSON.stringify(value)
  res.writeHead(status, { 'content-type': 'application/json; charset=utf-8' })
  res.end(body)
}

/** Read one document's full body file (variants merged), or undefined when absent. */
async function readDocumentFile(corpusDir: string, id: string): Promise<DocEntry | undefined> {
  try {
    const raw = await readFile(join(corpusDir, 'documents', `${id}.json`), 'utf8')
    const parsed = JSON.parse(raw) as { id: string; variants: Partial<Record<CorpusLocale, DocVariant>> }
    return {
      id: parsed.id,
      module: '',
      kind: 'misc',
      sourcePath: '',
      variants: parsed.variants,
    }
  } catch (error) {
    if ((error as { code?: string }).code !== 'ENOENT') throw error
    return undefined
  }
}

/** Parse a JSON request body (bounded). */
async function readJson(req: IncomingMessage): Promise<unknown> {
  const chunks: Buffer[] = []
  let size = 0
  for await (const chunk of req) {
    const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)
    size += buffer.length
    if (size > 1_000_000) throw new Error('request body too large')
    chunks.push(buffer)
  }
  return JSON.parse(Buffer.concat(chunks).toString('utf8'))
}

/** Mount the plugin. */
export function apply(ctx: Context, config: Config = {}): void {
  const service = new Dsh101Service(ctx, config.corpusDir ?? DEFAULT_CORPUS_DIR)
  ctx.effect(() => {
    const disposeService = ctx.reflect.provide('dsh101', service)
    return () => { void disposeService() }
  }, 'dsh-101-app: service')

  const handle = async (req: IncomingMessage, res: ServerResponse): Promise<void> => {
    const url = new URL(req.url ?? '/', 'http://dsh.internal')
    const path = url.pathname.replace(/^\/api\/dsh101/, '') || '/'
    try {
      if (req.method === 'GET' && path === '/index') {
        json(res, 200, { corpus: service.corpus, curationCurrent: service.curation.current })
        return
      }
      if (req.method === 'GET' && path.startsWith('/doc/')) {
        const id = decodeURIComponent(path.slice('/doc/'.length))
        // docFull merges the index metadata (module/kind/sourcePath) with the
        // per-document body file, so the reader gets complete entries.
        const doc = await service.docFull(id)
        if (doc === undefined) {
          json(res, 404, { error: `unknown document ${JSON.stringify(id)}` })
          return
        }
        json(res, 200, { doc })
        return
      }
      if (req.method === 'GET' && path.startsWith('/search')) {
        const query = url.searchParams.get('q') ?? ''
        json(res, 200, { result: service.search(query) })
        return
      }
      if (req.method === 'GET' && path.startsWith('/img/')) {
        const file = path.slice('/img/'.length).replace(/[^a-zA-Z0-9._-]/g, '')
        try {
          const data = await readFile(join(service.corpusDir, 'images', file))
          res.writeHead(200, {
            'content-type': mimeOf(file),
            'cache-control': 'public, max-age=31536000, immutable',
          })
          res.end(data)
        } catch {
          json(res, 404, { error: 'image not found' })
        }
        return
      }
      if (req.method === 'GET' && path === '/status') {
        json(res, 200, {
          corpusRevision: service.corpus.revision,
          dshVersion: service.corpus.dshVersion,
          curation: service.curation,
          jobToken: service.jobToken,
        })
        return
      }
      if (req.method === 'GET' && path.startsWith('/context')) {
        const sessionId = url.searchParams.get('sessionId') ?? ''
        json(res, 200, { context: sessionId === '' ? undefined : (service.getContext(sessionId) ?? null) })
        return
      }
      if (req.method === 'POST' && path === '/context') {
        const body = await readJson(req) as { sessionId?: unknown; docId?: unknown; section?: unknown }
        if (typeof body.sessionId !== 'string' || typeof body.docId !== 'string') {
          json(res, 400, { error: 'sessionId and docId are required' })
          return
        }
        service.setContext(body.sessionId, {
          docId: body.docId,
          ...(typeof body.section === 'string' ? { section: body.section } : {}),
        })
        json(res, 200, { ok: true })
        return
      }
      if (req.method === 'POST' && path === '/translate') {
        const body = await readJson(req) as { docId?: unknown; locale?: unknown; translation?: unknown }
        if (typeof body.docId !== 'string' || typeof body.locale !== 'string' || typeof body.translation !== 'string') {
          json(res, 400, { error: 'docId, locale, and translation are required' })
          return
        }
        const result = await service.saveTranslation({ docId: body.docId, locale: body.locale as CorpusLocale, body: body.translation })
        json(res, result.ok ? 200 : 400, result)
        return
      }
      if (req.method === 'GET' && path === '/translations') {
        json(res, 200, { bindings: service.translationBindings() })
        return
      }
      if (req.method === 'POST' && path === '/translate/bind') {
        const body = await readJson(req) as { docId?: unknown; sessionId?: unknown; locale?: unknown; title?: unknown }
        if (typeof body.docId !== 'string' || typeof body.sessionId !== 'string' || typeof body.locale !== 'string') {
          json(res, 400, { error: 'docId, sessionId, and locale are required' })
          return
        }
        const result = await service.bindTranslation({
          docId: body.docId,
          sessionId: body.sessionId,
          locale: body.locale as CorpusLocale,
          title: typeof body.title === 'string' ? body.title : body.docId,
        })
        json(res, result.ok ? 200 : 400, result)
        return
      }
      if (req.method === 'POST' && path === '/publish') {
        const body = await readJson(req) as { token?: unknown; curation?: unknown }
        const token = typeof body.token === 'string' ? body.token : ''
        const curation = typeof body.curation === 'object' && body.curation !== null
          ? parseCurationFile(JSON.stringify(body.curation))
          : undefined
        if (curation === undefined) {
          json(res, 400, { error: 'missing curation payload' })
          return
        }
        const result = await service.publish({ token, curation })
        json(res, result.ok ? 200 : 400, result)
        return
      }
      json(res, 404, { error: `unknown dsh101 endpoint ${JSON.stringify(path)}` })
    } catch (error) {
      json(res, 500, { error: error instanceof Error ? error.message : String(error) })
    }
  }

  ctx.effect(
    () => ctx.httpServer.register({ kind: 'prefix', path: '/api/dsh101', handler: handle }),
    'dsh-101-app: api routes',
  )
}

declare module 'cordis' {
  interface Context {
    dsh101: IDsh101
  }
}

